---
- name: A playbook to test reacheability
  hosts: ios
  gather_facts: no
  collections:
     - cisco.ios
  become: yes
  tasks: 
  - name: pinging to 192.168.154.188
      cisco.ios.ios_ping:
             dest: 192.168.154.188
      register: result
      
    - name: print result
      ansible.builtin.debug:
                    msg: "{{ result }}"
