---
- name: A playbook to test reacheability
  hosts: 192.168.154.130
  gather_facts: no
  become: yes
  tasks: 
  - name: pinging to 192.168.154.185
    cisco.ios.ios_ping:
             dest: 192.168.154.188
    register: result
      
  - name: print result
    ansible.builtin.debug:
               msg: "{{ result }}"
