---
- name: A playbook to test reacheability
  hosts: ios
  gather_facts: no
  vars:
    destination: 192.168.154.188
  tasks: 
    - name: "pinging to {{ destination }}"
      cisco.ios.ios_ping:
             dest: "{{ destination }}"
      register: result
      
    - name: print result
      ansible.builtin.debug:
                    msg: "{{ result }}"
